### ISSUE TITLE
about Google API keys

### ISSUE THREAD

**Issue by pipashu** [Alex313031/Thorium-Special#10]
Unable to implement Google account sign in and sync.

**Comment by Alex313031** [comment]
@pipashu Are you on the mac release?

**Comment by pipashu** [comment]
> 

yes,i on the mac release.

**Comment by Alex313031** [comment]
@pipashu You are the second person to make an issue. I think @midzer might have forgotten to include the API Keys in this release (he build the Mac versions since I don't have a mac) Its also possible that there are api keys that wont work, because we were experimenting with a different set of api keys. Either way, it should probably be resolved by next release.

Also, for all Thorium releases, make sure you are added to https://groups.google.com/u/1/a/chromium.org/g/google-browser-signin-testaccounts as per https://www.chromium.org/developers/how-tos/api-keys/#signing-in-to-chromium-is-restricted

**Comment by pipashu** [comment]
@Alex313031 thanks for your answer.

**Comment by Alex313031** [comment]
@pipashu Should be resolved now.
