### ISSUE TITLE
Experimental Windows on ARM64 Release - M105.0.5142.0 - No webpages displayed

### ISSUE THREAD

**Issue by mzinner** [Alex313031/Thorium-Special#15]
Hi Thorium-Team, 

I just got time to test the Windows on ARM64 build. I am trying to run it on a Windows 11 ARM64 Parallels VM on my MacBook Pro. While the Thorium window comes up as expected, no web pages are displayed, same for chrome://settings/

Instead the following can be read.

Aw, Fuck!
Something went wrong while displaying this webpage.
Error code: STATUS_BREAKPOINT

I tried to capture a log file but that does not show any specific errors it seems.
`.\thorium.exe --enable-logging=stderr --v=1 > log.txt 2>&1`

The Crashpad/reports directory in the user data dir also has a lot of reports. I will link one here.

- [Screenshot](https://zinner.org/temp/ThoriumWinArm64.png)
- [Log File](https://zinner.org/temp/log.txt)
- [Dump File](https://zinner.org/temp/d752994c-d405-4957-adbb-c9e349316ec8.dmp)

Please let me know how I can provide more useful info to get this working.

Thanks,
Mike

**Comment by Alex313031** [comment]
@mzinner This is strange, as another guy who originally requested the arm build got it to work fine, although this was on native hardware with windows 10. Unfortunately, official builds that I release to the public, as part of the optimizations thorium uses, have all debugging constructs removed, meaning that you cant debug it well, even with a dump file since it wont have stack traces, and log files only have high level information.

It might be that it is in a VM, either because of some VM weirdness, or because it is not passing the NEON instruction set onto the VM. The arm version for raspberry pi, MacOS M1, and windows on arm all have NEON enabled, which is a vector SIMD instruction set, kind of like AVX but for ARM. The x64 versions have AVX, so I saw it fitting to use NEON for performance improvements, but this means it can only run on an arm chip with armv8.1 or higher. If you have another machine, try it on a native arm machine. If not, Im not used to parallels, but see if you can find info on NEON or instruction set/virtualization passthrough.

**Comment by mzinner** [comment]
@Alex313031 Good questions. I just tried the Windows on ARM builds from [here](https://chromium.woolyss.com/#windows-on-arm) and they just work fine. Since they have been tuned by the Open Source Software group at Arm I would expect they also have enabled NEON support (but that is pure speculation on my side of course). Maybe an email to these [folks](mailto:chromium-win-dev@arm.com) would be helpful and they might share the compiler settings they are [using](https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/native-chromium-builds-windows-on-arm).

**Comment by Alex313031** [comment]
@mzinner We have been working on the Win On Arm. We got NEON working. A build will be coming soon.

Also, new Raspi release, with alot of new flags and patches! > https://github.com/Alex313031/Thorium-Special/releases/tag/M106.0.5215.0

**Comment by mzinner** [comment]
This is great news! It would mean I can use Thorium on all platforms I need. Please keep up the good work!

**Comment by Alex313031** [comment]
@mzinner In particular, this raspi release has patches to use the VC4 version of minigbm, instead of the default Intel one, so graphics performance should be better, and may enable hardware video acceleration for some codecs.

**Comment by Alex313031** [comment]
@mzinner @da-brad We are working on a new release for win on arm.

**Comment by Alex313031** [comment]
@mzinner @da-brad Can ya'll please test. I have no arm windows device. > https://github.com/Alex313031/Thorium-Special/releases/tag/M111.0.5563.111-3

**Comment by mzinner** [comment]
@Alex313031 Sorry for the late reply, I now had a chance to test both builds, v1 and v2 from [https://github.com/Alex313031/Thorium-Special/releases/tag/M111.0.5563.111-3](https://github.com/Alex313031/Thorium-Special/releases/tag/M111.0.5563.111-3) but both show the same error when trying to display any tab.

<img width="750" alt="Screenshot 2023-04-27 at 14 32 06" src="https://user-images.githubusercontent.com/37372663/234863496-72bcdd80-a3aa-4b64-bd58-03bb2bfc5323.png">

Is there any log i could enable to give you a better idea of what is causing this? [This article](https://www.xda-developers.com/google-holding-back-native-browsers-windows-on-arm/) suggests it is caused by Widevine and that all other Chromium-based browsers like Brave and Vivaldi don't offer their builds for Windows on ARM because of that.

Did you disable Widevine in those builds?

Thanks,
Mike
