### ISSUE TITLE
Thorium and Playwright Floss manager not present, cannot set Floss enable/disable

### ISSUE THREAD

**Issue by bobHealy** [Alex313031/Thorium-Special#26]
Thanks for this awesome work to compile Thorium to so many platforms. I'm trying to use thorium with [Playwright](https://playwright.dev/) in headless mode for testing and receiving an error. I know that Playwright is not your business but maybe you have a hint how to make it work?

I used the ARM build [Raspberry Pi Release - M107.0.5270.0](https://github.com/Alex313031/Thorium-Special/releases/tag/M107.0.5270.0)

`==================== Browser output: ====================

<launching> /usr/bin/thorium-browser --inspector-pipe --headless --no-startup-window
<launched> pid=12648
[pid=12648][err] [0927/091039.516571:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[pid=12648][err] [0927/091039.598862:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[pid=12648] <process did exit: exitCode=0, signal=null>
[pid=12648] starting temporary directories cleanup`

**Comment by Alex313031** [comment]
@bobHealy This is probably due to the fact that the raspi builds are using the VC4 version of mesa libraries. I added this patch to increase gpu performance and allow hardware video decoding, but it causes the gpu sandbox to behave out of the normal spec, and can cause unforseen consequences like the `InitializeSandbox() called with multiple threads in process gpu-process` in your error report. I dont use playwright, and have not tested it on any platforms. The only thing I have tested with browser automation for thorium is chromedriver (which is actually included in the install, along with thorium-shell and pak, over the baseline install that other chromium browsers have) on linux. You could maybe help me by installing this old version of thorium for raspi, and see if it works for that release > https://github.com/Alex313031/Thorium-Special/releases/tag/M102.0.4972.0
