### ISSUE TITLE
Feature request: Bring back the old tab layout on Android

### ISSUE THREAD

**Issue by People-11** [Alex313031/Thorium-Special#39]
From Chrome 93 or 9x (I can't remember) Google applied new tab grid layout for Chrome Android, and fully disabled the old, page-like tab layout. But I really love the old layout, so could you bring the old tab layout back in the next Android build?
![Screenshot_20230310-020730_Quickstep](https://user-images.githubusercontent.com/41558215/224067894-5d06f7df-3af6-4e6b-875a-7ac3428c43a2.png)

**Comment by Alex313031** [comment]
@People-11 Does bromite or kiwi or another chromium based android browser have this? Because i would be willing to add a patch, however, my expertise is mainly with desktop chromium development. The android builds are experimental, and I have not hardly any experience with .java files, which the android version uses heavily for styling its UI. If there is no patch or other place for information on how I would do this, Im afraid I simply dont have enough knowledge on the work and changes that would be entailed to restore this.

But yes, I agree with you, I prefer the pre-M9x series tab UI better as well.

**Comment by People-11** [comment]
@Alex313031 kiwi browser has page-like tab style by default, but slightly different from Chrome's one, and unfortunately bromite is the same as today's Chrome, can't revert to page-like style even disabled tab grid layout in flags

**Comment by Alex313031** [comment]
@People-11 Interesting
