### ISSUE TITLE
Text selection bug

### ISSUE THREAD

**Issue by toprak** [Alex313031/Thorium-Special#46]
When I select text, selection stuff does not show up

**Comment by midzer** [comment]
I can confirm this.

**Comment by gz83** [comment]
@midzer @toprak 

Do you guys have experimental flags open and also I would like to know what site you are having this problem on?

**Comment by midzer** [comment]
No flags at all. And it looks like it happens on every site...Linux M111 here.

**Comment by monarc99** [comment]
i can confirm this, but only with dark themes. e.g. here on github

with a white theme, everything works normal. If i switch to a dark theme, the selection is not visible, but is useable. You can copy the text, but you cannot see the selection.

**Comment by gz83** [comment]
@midzer @monarc99 

This problem is a bit strange, I have encountered a similar problem before after turning on an experimental flag

https://bugs.chromium.org/p/chromium/issues/detail?id=1412395

**Comment by toprak** [comment]
@gz83 I do have this flags enabled: `Enable Dark Mode`, `Show/Hide the Avatar Button`, `Smooth Scrolling`,`Enable the high efficiency mode feature in the settings`.

**Comment by gz83** [comment]
> @gz83 I do have this flags enabled: `Enable Dark Mode`, `Show/Hide the Avatar Button`, `Smooth Scrolling`,`Enable the high efficiency mode feature in the settings`.

@toprak 

Turn off all experimental flags and check again to see if the problem still exists.

**Comment by toprak** [comment]
@gz83 I turned every exp. flag off and it still persist

**Comment by Alex313031** [comment]
@toprak @midzer @monarc99 @gz83 It turns out this is an upstream bug, that only shows up when experimental web platform features are turned on, AND the page is dark mode, and only for sites that set custom text selection handlers (like GitHub). To fix it, either use light more, or turn experimental web platform features off.

For Windows and MacOS, this is at `chrome://flags/#enable-experimental-web-platform-features`

HOWEVER, on Linux I have actually added it to the wrapper that is called by the .desktop file or running it from the command line.

The fix is to edit `/opt/chromium.org/thorium/thorium-browser` and remove the "--enable-experimental-web-platform-features" part of the "exec" line towards the bottom.
