### ISSUE TITLE
How to enable Sync on Thorium for MacOS

### ISSUE THREAD

**Issue by The-Engineer** [Alex313031/Thorium-Special#5]
Hi Thorium team,

nn my work macbook (Monterey with Intel CPU) the google sync feature is deactivated in official Chrome. Installing the [Chromium.woolyss.com](https://chromium.woolyss.com/) Chrome v95 sync was possible, but there are no updates to it.

I then installed the Thorium special Release M102, it runs but sync is not available. Am I doing something wrong? Leftovers from the other Chromium? Is it ok to still have Chromium installed (don't need to)?

When I run Thorium, stop it and open Chromium again I am completely logged out of my Google account in Chromium.

Thanks for your help 
Felix

**Comment by Alex313031** [comment]
@The-Engineer Its not really a team its just me lol, but @midzer does make the mac builds since I dont have a mac (I use a vm for some source code things for the mac builds, but it would take days to compile in a VM).

This is the same issue as https://github.com/Alex313031/Thorium-Win/issues/9 so follow the instructions there.

**Comment by The-Engineer** [comment]
It now works in the newest release with the keys, thank you very much for your work
