### ISSUE TITLE
When I updated from M115.0.5790.172 to M116.0.5845.169, every time I start thorium, the window always flashes!

### ISSUE THREAD

**Issue by Sunsh4j** [Alex313031/Thorium-Special#67]
**System Details**
 - OS: [Windows 10]
 - Thorium Version [[M116.0.5845.169](https://github.com/Alex313031/Thorium-Special/releases/tag/M116.0.5845.169)]

**Problem**
I upgraded Thorium just now, but I'm having problems with the window flickering every time I start it up. I closed all browser extensions, restarted the system, but nothing solved the problem!
Also is it possible to cancel that search tab button in the top left corner of the browser, as there is already one in the top right corner of the browser?

![动画](https://github.com/Alex313031/Thorium-Special/assets/43169575/68b6e1e3-6a75-4824-9ca5-a04af3fd69fb)

**Comment by gz83** [comment]
Are you experiencing flickering when switching from incognito mode to normal mode?

In addition, try to restore the currently applied theme, NTP page background image, etc. to the default and see if this problem still occurs.

Regarding the issue with the icons in the upper left corner as well as the upper right corner, this is caused by the fact that you have CR23 turned on, as the icons located in the upper right corner were not removed when the code was frozen in version 116, and in the new version, the icons located in the upper right corner have been removed and will no longer exist, so just wait for the new version of Thorium to be released and this issue will be resolved.

@Sunshagon

**Comment by gz83** [comment]
I can't reproduce the problem you're having, you'll need to provide a more detailed video of the steps to reproduce it.

If you only want the icon to appear in the top right corner, you can only turn off the CR23 style for now. Also, the icon does not support deletion at this time, and I do not support modifying the logic of the icon at this stage as there is not a strong community demand for deleting or tweaking this icon.

@Sunshagon

**Comment by gz83** [comment]
Keep the user data, then uninstall the currently installed version and try reinstalling it.

@Sunshagon

**Comment by Alex313031** [comment]
@Sunshagon @gz83 He shouldn't have the CR23 design changes unless he turned them on. It doesn't roll out to stable until M120.
