### ISSUE TITLE
No sync with latest X64 Mac release

### ISSUE THREAD

**Issue by BlairSadewitz** [Alex313031/Thorium-Special#8]
Hi.

I tried M104.0.5079.0 today, and it seems that google's delicate sensibilities were offended by it, as it wouldn't sync--even with my own API keys.  I downgraded to 103.0.5037.0, everything was right as rain.  

Thanks for maintaining this, by the way.  It's my "daily driver" on all three supported platforms.

**Comment by Alex313031** [comment]
@BlairSadewitz Nice! Were you the guy on reddit with this issue? Do you mean linux, win and macos? 
I think midzer (who does the mac builds since I don't have a mac) might have forgot the api keys or mistyped them. When next release comes out we can try again and I will investigate if it still continues. And yeah, I daily drive it on all my platforms too. 

Also, check out new website for thorium which also has a new deb repo to support auto upgrading on linux! Me and midzer were hard at work today on this. > https://thorium.rocks/

Also, check out my OS project "ThoriumOS" which is a fork of ChromiumOS with compiler optimizations like thorium, extra packages, codecs/widevine, and kernel modules and drivers for more generic device support. > https://github.com/Alex313031/ChromiumOS/

**Comment by Alex313031** [comment]
@BlairSadewitz Should be resolved now.
